name = "menuflow"
pages_build_output_dir = "./dist"
compatibility_date = "2026-10-09"

[[d1_databases]]
binding = "DB"
database_name = "menuflow-db"
database_id = "73e694fd-8ca2-4b7a-825e-33930747eb90"
migrations_dir = "migrations"
